export type InvoicePresentationInputInterface = {
  id: string;
  external_id: string | null;
  vendor: Partial<VendorInterface>;
  vendor_id: string | null;
  vendor_trade_name: string | null;
  due_date: string | null;
  created_at: string;
  posting_date: string | null;
  discount_percent: string;
  invoice_total: string;
  invoice_total_in_system_currency: string;
  invoice_total_in_foreign_currency: string;
  total_vat_tax: string;
  total_vat_tax_in_system_currency: string;
  total_vat_tax_in_foreign_currency: string;
  vat_tax_percent: string;
  base_amount: string;
  total_discount_amount: number | null;
  total_discount_amount_in_system_currency: number | null;
  total_discount_amount_in_foreign_currency: number | null;
  total_down_payment_amount: number | null;
  total_down_payment_amount_in_system_currency: number | null;
  total_down_payment_amount_in_foreign_currency: number | null;
  paid_to_date_amount: number | null;
  paid_to_date_amount_in_system_currency: number | null;
  paid_to_date_amount_in_foreign_currency: number | null;
  additional_expenses: number | null;
  additional_expenses_in_system_currency: number | null;
  additional_expenses_in_foreign_currency: number | null;
  notes: string | null;
  external_ap_invoice_number: string | null;
  reference_number_external: string | null;
};

type VendorInterface = {
  id: string;
  external_id: string;
  visual_id: string;
  name: string;
  mail_to_address: string;
  bill_to_address: string;
  phone1: string;
  phone2: string;
};
