export interface TenantAccuracySettingsInputInterface {
  id: number;
  external_id: string | null;
  company_name: string | null;
  address: string | null;
  country_code: string | null;
  country_external_code: string | null;
  header: string | null;
  primary_phone_number1: string | null;
  primary_phone_number2: string | null;
  primary_email: string | null;
  local_currency_id: string | null;
  local_currency_external_id: string | null;
  system_currency_id: string | null;
  system_currency_external_id: string | null;
  open_balance_with_minus_sign: boolean;
  totals_accuracy_digits: number | null;
  quantities_accuracy_digits: number | null;
  prices_accuracy_digits: number | null;
  rates_accuracy_digits: number | null;
  percentages_accuracy_digits: number | null;
  measuring_units_accuracy_digits: number | null;
  query_accuracy_digits: number | null;
  decimal_separator: string | null;
  thousands_separator: string | null;
  display_currency_on_the_right: boolean;
  rounding_method: boolean;
  state: string | null;
  alias_name: string | null;
  address_type: string | null;
  street_number: string | null;
  date_of_incorporation: string | null;
  global_location_number: string | null;
  created_at: string;
  updated_at: string | null;
  created_by: string;
  updated_by: string | null;
  first_pull_sync_at: string | null;
  last_pull_sync_at: string | null;
  first_push_sync_at: string | null;
  last_push_sync_at: string | null;
}
